# Generated by Django 3.2.23 on 2023-12-04 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default=uuid.UUID('c9536a03-b8bb-43d9-ad63-8f87cc02e903'), max_length=50, unique=True),
        ),
    ]
