# Generated by Django 4.1.12 on 2023-10-28 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_game"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                ("portfolio_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("created_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="PlayerProfile",
            fields=[
                (
                    "player_profile_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("starting_balance", models.FloatField()),
                ("current_balance", models.FloatField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.game"
                    ),
                ),
                (
                    "portfolio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.portfolio",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Holding",
            fields=[
                ("holding_id", models.AutoField(primary_key=True, serialize=False)),
                ("stock_symbol", models.CharField(max_length=20)),
                ("purchase_date", models.DateField()),
                ("shares", models.IntegerField()),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.portfolio",
                    ),
                ),
            ],
        ),
    ]
