# Generated by Django 3.2.23 on 2023-12-04 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default=uuid.UUID('a4264ee3-e30a-4169-8d48-4173e414c2b3'), max_length=50, unique=True),
        ),
    ]
