# Generated by Django 4.1.12 on 2023-11-30 20:18

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_portfolio_playerprofile_holding"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("4fb3de89-2148-4837-a544-603feb555acc"),
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="players",
            field=models.ManyToManyField(
                related_name="games_played", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
