# Generated by Django 3.2.23 on 2023-12-04 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default=uuid.UUID('0376a44c-359a-4cda-89af-3394759be7b1'), max_length=50, unique=True),
        ),
    ]
