# Generated by Django 4.1.12 on 2023-11-30 21:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_customuser_user_id_game_players_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("75c5c024-be4a-46b3-aa8e-32519fa9b471"),
                max_length=50,
                unique=True,
            ),
        ),
    ]
