# Generated by Django 3.2.23 on 2023-12-04 02:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default=uuid.UUID('7ccafe90-c12c-4c83-9e60-03666ed00d39'), max_length=50, unique=True),
        ),
    ]
