# Generated by Django 4.1.13 on 2023-12-04 16:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_auto_20231204_0817"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("a318bdc6-74e5-4716-92b3-c71243fe37b7"),
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="join_string",
            field=models.CharField(
                default=uuid.UUID("61c6e1df-e8a2-453e-9ceb-272ea84eefbe"),
                max_length=50,
                unique=True,
            ),
        ),
    ]
