# Generated by Django 3.2.23 on 2023-12-04 02:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_customuser_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AddField(
            model_name='game',
            name='player_profiles',
            field=models.ManyToManyField(related_name='games_played', to='myapp.PlayerProfile'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default=uuid.UUID('cbce4b6a-09b3-42be-9207-67441b7cc850'), max_length=50, unique=True),
        ),
    ]
