# Generated by Django 3.2.23 on 2023-12-04 18:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20231204_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default=uuid.UUID('c458f2ea-0c3c-43c6-9ef7-35dbc6440d75'), max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='join_string',
            field=models.CharField(default=uuid.UUID('86d0d6ca-da3f-4da8-bf83-61fb90bb1d21'), max_length=50, unique=True),
        ),
    ]
