# Generated by Django 3.2.23 on 2023-12-04 18:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20231204_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default=uuid.UUID('6496713a-329a-4d04-a5a4-8b3d6e737bd6'), max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='join_string',
            field=models.CharField(default=uuid.UUID('aeaba5fb-40df-4b4f-a6b1-3b5556bc1d80'), max_length=50, unique=True),
        ),
    ]
