# Generated by Django 3.2.23 on 2023-12-05 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_customuser_user_id_alter_game_join_string'),
        ('myapp', '0009_auto_20231204_1848'),
    ]

    operations = [
    ]
